# Site settings
title: Haofeng Li 李灏峰
email: lhaof@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  'I am working as a research scientist in Shenzhen Research Institute of Big Data, The Chinese University of Hong Kong (Shenzhen). My research interests are medical image analysis, computer vision and deep learning. I am searching for students that are planning to pursue a MPhill degree in SRIBD, CUHK(SZ) under my supervision.'

baseurl: ""
url: "https://example.com"
phone: "07800 100100"
theme-path: theme-assets # path to header assets etc
map-api-key: AIzaSyB3U7uwIvCyq01orxppAIC1v73y-FBGygY
sass:
  sass_dir: _sass
  style: compressed

collections:
  case:
    output: true
    permalink: /case-studies/:path/
  resource:
    output: true
    permalink: /resources/:path/

# Build settings
markdown: kramdown
